### ISSUE TITLE
Couldn't get config from application meta data

### ISSUE THREAD

**Issue by niqo01** [Smartling/android-repository#3] opened 2017-02-14 22:31 UTC
I am seeing the following issue:
```
FATAL EXCEPTION: main
                  Process: com.couchsurfing.mobile.debug, PID: 9934
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.couchsurfing.mobile.debug/com.couchsurfing.mobile.ui.WelcomeActivity}: java.lang.RuntimeException: Couldn't get config from application meta data. Was it set on your build.gradle file?
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: java.lang.RuntimeException: Couldn't get config from application meta data. Was it set on your build.gradle file?
                      at com.smartling.android.sdk.core.CoreImpl.a(SourceFile:46)
                      at com.smartling.android.sdk.core.CoreImpl.<init>(SourceFile:34)
                      at com.smartling.android.sdk.core.CoreImpl.getInstance(SourceFile:63)
                      at com.smartling.android.sdk.Smartling.proxy(SourceFile:56)
                      at com.couchsurfing.mobile.ui.WelcomeActivity.attachBaseContext(WelcomeActivity.java:0)
                      at android.app.Activity.attach(Activity.java:6615)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

My config (2.2.3):
```
smartling {
  projectId = "93e7b42e8"
  auth {
    userIdentifier = "XX"
    userSecret = "XX"
  }
  mode = "context-capture"
  logLevel = "verbose"
}
```

**Comment by andriipanasiuk** [comment] 2017-02-15 11:22
Well, this exception is thrown on the line
`context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);`
which is very strange since it means 
`getApplicationInfo()` method threw `PackageManager.NameNotFoundException`.
Let's make a private Skype talk so I could learn any specific details from your project.
Skype Id: `andriipanasiuk`

**Comment by niqo01** [comment] 2017-02-17 22:48
Isn't is because I did not declare a meta `com.smartling.project.config` in my manifest?
The documentation here: https://github.com/Smartling/android-repository does not say to add one.

**Comment by andriipanasiuk** [comment] 2017-02-18 09:41
No, generally you don't have to do this. This configuration is exposed to manifest via Smartling plugin which you should apply in your `build.gradle` file. Since this exception took place in `attachBaseContext` method it means plugin was applied and has worked correctly. Plugin itself takes the appropriate configuration from `smartling` block in `build.gradle` file which you also have added as needed.
All to all it seems you made a correct setup. That's why I suggest there is some specific in your project which we're missing. It would be reliable and faster to discuss it in the chat.

**Comment by niqo01** [comment] 2017-02-27 23:17
Hi @andriipanasiuk 
I am sorry this last few weeks have been really busy here. Hopefully I ll be able to spare some more time soon.
I updated to 2.3.0 and still the same issue.
My project is a common one using Gradle and Android studio. We have 3 product flavors and 2 variants. Each product flavors override the applicationId.

**Comment by andriipanasiuk** [comment] 2017-02-28 11:21
Okay, let me try the same configuration you are using (with 3 product flavors each overriding `applicationId`).

**Comment by andriipanasiuk** [comment] 2017-02-28 14:05
I've tried a configuration with 3 product flavors and unfortunately can't reproduce your issue. 
Let's try it another way.

Since the crash is caused by 
```java
context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
```
and the `context` variable is coming from `attachBaseContext()` method of `Activity`, could you insert the following code into your `WelcomeActivity` and start the app.
```java
@Override
protected void attachBaseContext(Context context) {
    if (this.getBaseContext() == null) {
        super.attachBaseContext(context);
    }
    Log.d("Test", "Package name: " + context.getPackageName());
    try {
        ApplicationInfo info = context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
    } catch (PackageManager.NameNotFoundException e) {
        throw new RuntimeException(e);
    }
}
```
Thus, we'll see the logcat output and check if it doesn't cause an exception throwing.
Before doing that, remove please Smartling plugin applying from your `build.gradle` file.
Thanks!

**Comment by niqo01** [comment] 2017-02-28 19:20
There are no crashes when removing the plugin and adding your code
```
Package name: com.couchsurfing.mobile.debug
```
The crash is not coming from `context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);`
My guess is that  `var1.metaData.getString("com.smartling.project.config")` return null because if you look at the generated AndroidManifest there is no `com.smartling.project.config`

**Comment by niqo01** [comment] 2017-02-28 19:24
The cause is also missing when raising:
```
 throw new RuntimeException("Couldn\'t get config from application meta data. Was it set on your build.gradle file?");
```
THis exception is missing the cause.

**Comment by andriipanasiuk** [comment] 2017-03-02 16:35
Hi, Nicolas. @niqo01 
Yes, now I see, you are right, it's because there wasn't inserted `metadata` as expected into your `AndroidManifest.xml` file which had to be inserted with Smartling plugin code. I greatly appreciate your help and will definitely rework the piece of code where that `RuntimeException` is throwing since it's confusing a bit.
I created custom build of our plugin with additional logging to identify the issue and to understand why that metadata isn't exposed into your manifest.
To use it please do the following:
- in the `buildscript` section of your app's `build.gradle` use changed repo and version name for the plugin dependency
```groovy
buildscript {
    ...
    repositories {
        ...
        maven { url "https://raw.githubusercontent.com/Smartling/android-repository/snapshots" }
    }
    dependencies {
       ...
       classpath "com.smartling.android:plugin:2.3.0-COUCHSURFING-SNAPSHOT"
    }
}
```
- execute `./gradlew app:clean app:assemble{flavor_name}Debug` command
- give me the log outputs started with `Smartling:` string

Thank you a lot!

**Comment by niqo01** [comment] 2017-03-07 18:52
I replaced user id and secret with XX
```
Smartling: Config for playUiTest: SmartlingConfig{name='playUiTest', logLevel='verbose', mode='context-capture', otaServing=null, auth=Auth{userIdentifier='XX', userSecret='XX'}}
Smartling: Add process manifest action to playUiTest
Smartling: Config for playDebug: SmartlingConfig{name='playDebug', logLevel='verbose', mode='context-capture', otaServing=null, auth=Auth{userIdentifier='XX', userSecret='XX'}}
Smartling: Add process manifest action to playDebug
Smartling: Config for playRelease: SmartlingConfig{name='playRelease', logLevel='verbose', mode='context-capture', otaServing=null, auth=Auth{userIdentifier='XX', userSecret='XX'}}
Smartling: Add process manifest action to playRelease
Smartling: Config for playDevUiTest: SmartlingConfig{name='playDevUiTest', logLevel='verbose', mode='context-capture', otaServing=null, auth=Auth{userIdentifier='XX', userSecret='XX'}}
Smartling: Add process manifest action to playDevUiTest
Smartling: Config for playDevDebug: SmartlingConfig{name='playDevDebug', logLevel='verbose', mode='context-capture', otaServing=null, auth=Auth{userIdentifier='XX', userSecret='XX'}}
Smartling: Add process manifest action to playDevDebug
Smartling: Config for playDevRelease: SmartlingConfig{name='playDevRelease', logLevel='verbose', mode='context-capture', otaServing=null, auth=Auth{userIdentifier='XX', userSecret='XX'}}
Smartling: Add process manifest action to playDevRelease
```
Later
```
Smartling: Start Transforming Manifest at /home/niqo/workspace/couchsurfing/couchsurfing-android/app/build/intermediates/manifests/full/playDev/debug/AndroidManifest.xml
Smartling: Manifest parsed
Smartling: Metadata created and parsed
Smartling: Metadata node has been added to original manifest
Smartling: Modified manifest has been written to its file
```

**Comment by dmapr** [comment] 2017-03-14 18:58
I have run into this issue as well. What's really strange is that in my case

- The meta-data tag is generated and does appear in the manifest as expected
- This only happens in the debug variant, not in the release
- Commenting out the Smartling plugin and placing the generated value in the manifest manually works in the debug mode as well

The only thing that I have noticed that is different in the generated manifest file is that in the debug version we use Leak Canary and the following items are generated in the manifest preceding the Smartling meta-data tag:
`        <service android:enabled="false" android:name="com.squareup.leakcanary.internal.HeapAnalyzerService" android:process=":leakcanary"/>
        <service android:enabled="false" android:name="com.squareup.leakcanary.DisplayLeakService"/>

        <activity android:enabled="false" android:icon="@drawable/leak_canary_icon" android:label="@string/leak_canary_display_activity_label" android:name="com.squareup.leakcanary.internal.DisplayLeakActivity" android:taskAffinity="com.squareup.leakcanary" android:theme="@style/leak_canary_LeakCanary.Base">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:enabled="false" android:icon="@drawable/leak_canary_icon" android:label="@string/leak_canary_storage_permission_activity_label" android:name="com.squareup.leakcanary.internal.RequestStoragePermissionActivity" android:taskAffinity="com.squareup.leakcanary" android:theme="@style/leak_canary_Theme.Transparent"/>
`
I printed out the entire metadata in the Application.onCreate() and all metadata **except** for the smartling one is there if I let the plugin generate it. If I add it manually, then all metadata **including** the smartling one is accessible in code. Ditto in the release variant where the leak canary stuff isn't addedd.

**Comment by andriipanasiuk** [comment] 2017-03-20 10:11
Hey @dmapr! Sorry for late response.
So, for which build variant Smartling plugin **does** generate metadata in your case and for which **doesn't**?

**Comment by dmapr** [comment] 2017-03-20 14:25
Hi @andriipanasiuk,

sorry I wasn't quite clear. The metadata gets generated in **ALL** cases, what is different is that in the **debug** version the app can't read it.

**Comment by andriipanasiuk** [comment] 2017-03-20 15:09
@dmapr thanks, working on that.
Could you then send me the final generated manifest for **debug** variant (from `intermediates/manifests/full` folder)? Possibly with obfuscated code you don't want to expose but still retaining its structure.
_apanasiuk@smartling.com_
Thank you!

**Comment by dmapr** [comment] 2017-03-20 15:57
@andriipanasiuk, I think it may actually have something to do with the way Android Studio builds and deploys the APK. If I build the APK from the command line, it works fine.
Attaching a full (practically empty) project that reproduces the problem when running the debug build from the Studio.

[SmartlingMDN.zip](https://github.com/Smartling/android-repository/files/855559/SmartlingMDN.zip)

**Comment by andriipanasiuk** [comment] 2017-03-20 16:31
I've just tried the sample project you sent me. Just pressed `Run` button from Android Studio and it was launched appropriately.
So, you do the same and this very plain app crashes on its launch, right?
What OS and Android Studio version are you using?
By the way, here is the generated manifest for **debug** after I launched the app.
[AndroidManifest.xml](https://gist.github.com/andriipanasiuk/f1c872a5237703603dc9a3efe210cfb1)
Send me please yours.
Thanks a lot!

**Comment by dmapr** [comment] 2017-03-20 22:32
@andriipanasiuk, sorry about all the red herrings. It seems that the issue is only happening when Android Studio uses instant run. The AndroidManifest.xml generated in the **instant-run** config is missing the metadata tag. I've never seen the instant-run config before, perhaps something introduced in the latest version of Android Studio.

Android Studio version 2.3 running on Ubuntu 16.04, launching the app on Nexus 5 6.0.1
[manifests.zip](https://github.com/Smartling/android-repository/files/856554/manifests.zip)

**Comment by andriipanasiuk** [comment] 2017-03-21 08:16
@dmapr Yep, now I see - `AndroidManifest.xml` file for the instant-run case is missing Smartling `<metadata/>` tag while regular one has it. 
I will figure out how to fix it. For now, the solution is not to use Instant Run if it's reliable for your purposes.
@niqo01 Is your issue reproduced in the same way? (Instant Run only)

**Comment by niqo01** [comment] 2017-03-21 18:31
@andriipanasiuk This way worked for me too.

**Comment by dmapr** [comment] 2017-03-21 18:42
The good news is that @andriipanasiuk has discovered how to work with the instant run config so we should see it in the next plugin update, right? :)

**Comment by andriipanasiuk** [comment] 2017-03-22 10:55
Hello guys! @dmapr @niqo01 
You are welcome to use new version **2.3.1** with Instant Run enabled as well as with disabled.
I appreciate your help in this issue resolving.

Give me please your confirmations about all is working properly so I can close this issue.
Thank you!

**Comment by dmapr** [comment] 2017-03-22 16:12
Thanks @andriipanasiuk! I can confirm 2.3.1 has fixed the issue for me.

**Comment by andriipanasiuk** [comment] 2017-03-27 09:50
Hello @niqo01 !
Does **2.3.1** fix your issue?

**Comment by andriipanasiuk** [comment] 2017-03-29 20:47
Okay, I believe the crash from Nicolas had the same reason so I'm closing this issue. Thank you guys for your help!

**Closed by andriipanasiuk** 2017-03-29 20:47 UTC
Labels: enhancement
